### ISSUE TITLE
Bug, Subqueries losing parethesis causing bad mysql  

### ISSUE THREAD

**Issue by phyzical** [kddnewton/active_record-union_relation#126]
Hey there,

ran into a bug trying to upgrade from 0.1.1 to 0.3.0, for some reason the .ast call is causing the subqueries to come out without '(' and ')' causing mysql to moan

```
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT
	'SomeClass' AS `discriminator`,
	id AS `id`,
	name AS `name`' at line 12
```

i.e 
0.3.0
```
SELECT
	discriminator,
	id,
	name,
	active
FROM
	SELECT
	'SomeClass' AS `discriminator`,
	id AS `id`,
	name AS `name`,
	active AS `active`,
FROM
	`some_class
WHERE
	`some_class`.`archived` = FALSE AS `union`
```

vs 0.1.1
```
SELECT
	discriminator,
	id,
	name,
	active
FROM
	(SELECT
	'SomeClass' AS `discriminator`,
	id AS `id`,
	name AS `name`,
	active AS `active`,
FROM
	`some_class
WHERE
	`some_class`.`archived` = FALSE) AS `union`
```

https://github.com/kddnewton/active_record-union_relation/compare/v0.1.1...v0.2.0#diff-47adbb2bbca246dbac44f2bca68ef94a45c91ae6a08abeef5b2b691411a16f22L116-R147

i also confirmed by monkey patching that it does work again if i remove `.ast`

Just wanted to check if there wasn't something else on my end that may cause this logic to breakdown? if not ill look at making a pr with a test at some point

Thanks!

**Comment by phyzical** [comment]
https://github.com/kddnewton/active_record-union_relation/pull/127

I was able to replicate though im not sure how/why this happens but https://github.com/kddnewton/active_record-union_relation/pull/127/files#diff-40822d3ce62238e7a2518e9702da9aee1937baf6c98c798d10a589cece71ffd1R87

If you comment out this line it will pass OR if you remove the `.ast` core over in https://github.com/phyzical/active_record-union_relation/blob/fa709707dafcac613113a98edb4a13eaadd22fff/lib/active_record/union_relation.rb#L201

**Comment by kddnewton** [comment]
Thank you! The test case was very helpful. I've opened a fix for this.

**Comment by phyzical** [comment]
Confirmed our tests pass without the monkey patch in 0.3.1 thanks again!
